{
  "module": "Test",
  "kind": "Linearity Error",
  "text": [
    { "type": "text", "content": "The " },
    { "type": "text", "content": " variable " },
    { "type": "code", "content": "r" },
    { "type": "text", "content": " was " },
    {
      "type": "text",
      "content": "consumed in the loop, without afterwards being reassigned."
    }
  ],
  "span": {
    "filename": "test-programs/suites/006-linearity/007-outside-for-loop/Test.aum",
    "startp": { "line": 8, "column": 8 },
    "end": { "line": 10, "column": 16 }
  },
  "context": [
    [ 6, "    function main(): ExitCode is" ],
    [ 7, "        let r: R := R(x => 32);" ],
    [ 8, "        for i from 0 to 10 do" ],
    [ 9, "            let { x: Int32 } := r;" ],
    [ 10, "        end for;" ],
    [ 11, "        return ExitSuccess();" ],
    [ 12, "    end;" ]
  ]
}